name: crop_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider:
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences:
  http:
  dotted_border: ^2.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/home/images/
    - assets/home/plants/
    - assets/onboarding/images/
    - assets/geo/us_counties_simplified.json